#!/bin/bash

# Create a short delay so changes in brightness can be registered
sleep 0.2

# Get the brightness percentage:
BRIGHTNESS_VALUE=$(cat /sys/class/backlight/intel_backlight/brightness)

# Round the brightness percentage:
B_P=$(($BRIGHTNESS_VALUE *100 / 4882))
LC_ALL=C
#BRIGHTNESS_VALUE=$(printf "%.*f\n" 0 $BRIGHTNESS_VALUE)
BRIGHTNESS_VALUE=$(printf "%.*f\n" 0 $B_P)

# Kill previous notifications so the brightness notifications don't pile up:
killall -q mate-notification-

BRIGHTNESS="Brightness"

# Send the notification with the icon:
notify-send `echo $BRIGHTNESS: $BRIGHTNESS_VALUE` \
        -t 1000 -i ~/.config/i3/icons/brightness-icon.png
