#!/bin/bash

# Display startup script.
# Different settings for different laptops.
# If the monitor is connected via HDMI, display only that.
# If the monitor is disconnected, display from laptop screen only.

HOST=$(hostname)

        LAPTOP=eDP-1
        LAPTOP_RES_HDMI_ON=1920x1080
        LAPTOP_RES_HDMI_OFF=2560x1440
        EXTERNAL=HDMI-2

function dual-displays {
        xrandr --output $LAPTOP --mode $LAPTOP_RES_HDMI_ON \
               --output $EXTERNAL --mode 1360x768 --left-of $LAPTOP 
                #	workspace 1 output HDMI-2
}

function monitor-only {
        xrandr --output $EXTERNAL --mode 1920x1080 --output $LAPTOP --off
}

function display-on-laptop-only {
        xrandr --output $EXTERNAL --off --output $LAPTOP \
                --mode $LAPTOP_RES_HDMI_ON
}

function hdmi-is-connected {
        ! xrandr | grep "^$EXTERNAL" | grep disconnected
}

if hdmi-is-connected & [[ "$HOST" == "debian" ]]; then
        monitor-only & monitor-fonts
        # dual-displays
elif hdmi-is-connected; then
        dual-displays
else
        display-on-laptop-only 
	#& laptop-fonts
fi
