#!/bin/bash

# If WiFi is connected, show the WiFi symbol as green.
# If it's disconnected, show it as red. If dormannt, as yellow.

# The desktop doesn't connect to WiFi
if [[ $(hostname) == "m73" ]]; then
        exit 0
else
        if [[ $BLOCK_BUTTON == '1' ]]; then
                nm-connection-editor
        fi
        if [[ $BLOCK_BUTTON == '3' ]]; then
                SSID=`sudo iwconfig wlp4s0 | grep "ESSID" | cut -d ":" -f2`
                FREQ=`sudo iwconfig wlp4s0 | grep Frequency | cut -d 'G' -f1 | \
                        cut -d ':' -f3`
                LOCAL_IP=`sudo ifconfig wlp4s0 | grep 'inet addr' | cut -d ":" -f2 | \
                        cut -d "B" -f1`
                notify-send "`echo -e 'SSID: ' $SSID'\nFrequency: ' $FREQ'\nLocal IP: '$LOCAL_IP`" \
                        -i /usr/share/icons/Numix-Circle/48x48/apps/networkmanager.svg
        fi
        if [[ $BLOCK_BUTTON == '4' ]] | [[ $BLOCK_BUTTON == '5' ]]; then
                notify-send "`echo $(macchanger wlp4s0 -s)`" \
                        -i /usr/share/icons/Numix-Circle/48x48/apps/networkmanager.svg
        fi

        wlan_state="$(cat /sys/class/net/wlp4s0/operstate)"

        if [ "$wlan_state" = "up" ]; then
                echo ""
                echo ""
                exit 0
        elif [ "$wlan_state" = "down" ]; then
                echo ""
                echo ""
                echo "#DC322F"
                exit 0
        elif [ "$wlan_state" = "dormant" ]; then
                echo ""
                echo ""
                echo "#F99157"
                exit 0
        fi
fi
